# Generated by Django 4.1.3 on 2022-11-16 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Electrodomestico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_electrodomestico', models.CharField(max_length=30)),
                ('precio', models.IntegerField()),
                ('especificaciones', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Garantia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reparacion', models.CharField(max_length=30)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('nombre_usuario', models.CharField(max_length=30)),
                ('contrasenia', models.CharField(max_length=30)),
            ],
        ),
    ]
