# Generated by Django 4.1.3 on 2022-11-22 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_electrodomesticos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_electrodomestico', models.CharField(max_length=30)),
                ('precio', models.IntegerField()),
                ('observaciones', models.CharField(max_length=600)),
            ],
        ),
        migrations.DeleteModel(
            name='Electrodomestico',
        ),
    ]
