# Generated by Django 4.1.3 on 2022-11-22 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_electrodomesticos', '0002_producto_delete_electrodomestico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='tipo_electrodomestico',
            new_name='nombre_producto',
        ),
    ]
