# Generated by Django 4.1.3 on 2022-11-26 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_electrodomesticos', '0003_rename_tipo_electrodomestico_producto_nombre_producto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producto',
            new_name='Product',
        ),
    ]
