# Generated by Django 4.1.3 on 2022-11-26 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_electrodomesticos', '0004_rename_producto_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Producto',
        ),
    ]
